name: Auto Scrape M3U

on:
  schedule:
    - cron: '0 */1 * * *' # Chạy mỗi tiếng
  workflow_dispatch:      # Bấm tay chạy được

jobs:
  run-bot:
    runs-on: ubuntu-latest
    permissions:
      contents: write     # Cho phép bot ghi file vào repo

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          pip install playwright playwright-stealth PyGithub requests beautifulsoup4
          playwright install chromium

      - name: Execution
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          GH_REPO: ${{ github.repository }}
        run: python main.py
